### PR TITLE
Update return value in case of MySQLdb.error

### PR DESCRIPTION
**Pull request by humblearner**
Fix for #4

### CODE REVIEW

**Comment by LindsayHill** [comment]
Nice - 👍

**Comment by humblearner** [comment]
@LindsayHill: I personally like [solution 2](https://github.com/StackStorm-Exchange/stackstorm-mysql/issues/4#issuecomment-303258461) because it is more explicit, but i'll let you all decide.

**Comment by LindsayHill** [comment]
I like that solution 1 gives you a cleaner error message, without the additional traceback (which just confuses most people).

But it doesn't seem right that solution 1 returns exit code 0. Seems it would be better to return exit code 1, so that a workflow could pick up the failure?

**Comment by Kami** [comment]
If we don't need to return any structured data with a failure (e.g. a dict or other complex type), I think throwing exception is better.

First option (returning status failed == True) is more meant to be user when you need to return some structured data with a failure.

**Pull request merged**
